[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines = 1

  [[http_service.checks]]
    interval = "10s"
    timeout  = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
